### ISSUE TITLE
Support for Media

### ISSUE THREAD

**Issue by tahafatih** [zorapeteri/react-tweet-card#5]
Hi @zorapeteri,

First of all, thank you very much for this package. Is it possible to add media to tweets like in the example below?

<img width="893" alt="Tweet by Tim Cook" src="https://user-images.githubusercontent.com/45592550/217969368-9921ef2d-eade-4941-a9e4-c1ed44bb5274.png">

<img width="893" alt="Tweet by SpaceX" src="https://user-images.githubusercontent.com/45592550/217969502-4d315c89-01a9-4289-8167-6d2e28ea61bd.png">

**Comment by zorapeteri** [comment]
hey @tahafatih,

this is not a feature at the moment, but if you feel like taking a look inside the package a bit and raising a PR for this that would totally be cool. if you don't feel like doing that and really need this right away, i suppose you could hack an image into the component using the exposed classnames and some CSS, like so:

```css
.react-tweet-card__tweet:after {
        display: block;
        content: '';
        margin-top: 20px;
        height: 9em;
        width: 100%;
        background-image: url(https://www.savoredjourneys.com/wp-content/uploads/2020/06/road-trip-iceland.jpg);
        background-size: cover;
        background-position: center center;
        background-repeat: no-repeat;
    }
```
